use_frameworks!

platform :ios, '12.0'

# 自己弄的私有源

# source 'https://github.com/evernoteHW/MySpecsTest.git'

target 'AMMediator_Example' do
  
#  pod 'AMMediator', '0.2.0'
  pod 'AMMediator', :path => '../'

 # 指定版本的更新
# pod 'AMMediator', '0.1.0', :source => 'https://github.com/evernoteHW/MySpecsTest.git'
  
  # , :souce => 'https://github.com/evernoteHW/MySpecsTest.git'
  #  二进制
#  pod 'BlocksKit'
 
  target 'AMMediator_Tests' do
    inherit! :search_paths

    
  end
end
